cc_library(
    name = "functions",
    srcs = ["functions.cc"],
    hdrs = ["functions.h"],
)

cc_test(
    name = "functions_test",
    srcs = ["functions_test.cc"],
    deps = [
        ":functions",
        "@catch2//:catch2_main",
    ],
)
